version: '3.8'

services:
  # Serviço PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spark_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Interface gráfica PostgreSQL (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - app-network

  # Serviço RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"  # Porta para acesso ao painel de gerenciamento
    networks:
      - app-network

  # Serviço Go (aplicação Go)
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=spark_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
